version: '3.8'
services:
  cassandra-db:
    image: cassandra:latest
    container_name: cassandra-museo
    ports:
      - "9043:9042"
    volumes:
      - ./scripts/cassandra:/scripts
    environment:
      - CASSANDRA_CLUSTER_NAME=MuseoCluster
    restart: always

  mongo-db:
    image: mongo:7.0
    container_name: mongo-museo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=galeria_db_mongo
    restart: always

volumes:
  mongo_data:
